### ISSUE TITLE
ASE NeighborList API changed in latest version (3.16)

### ISSUE THREAD

**Issue by eickenberg** [atomistic-machine-learning/SchNet#2]
Hi,

I was trying to run the qm9 dataset loader, and it didn't work, telling me that the ASE `NeighborList` object has no such method as `build`.

It looks like the API of that particular class underwent significant changes in the last version, compare:

now: https://gitlab.com/ase/ase/blob/3.16.0/ase/neighborlist.py#L823

before for a long time: https://gitlab.com/ase/ase/blob/3.15.0/ase/neighborlist.py#L57

You may want to either indicate a version in your requirements, or file an issue with the ASE developers.

**Comment by ktschuett** [comment]
Thanks, I changed it to the new ASE call `update`. It still works with the old versions, as update calls `build` there.

340e781a850ef1d5c35aa9ab77b383e397b2f8ce
